name: namer_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  image_picker: ^1.0.7
  location: ^5.0.3
  google_maps_flutter: ^2.5.3
  http: ^1.2.1
  shared_preferences: ^2.2.2
  mime: ^1.0.4
  flutter_sound: ^9.2.13  # Para grabar audio
  permission_handler: ^11.0.1  # Para permisos de micrófono
  path_provider: ^2.1.1  # Para obtener directorios del dispositivo
  audioplayers: ^5.2.1  # Para reproducir el audio grabado

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/